# FitSense Desktop Configuration
# URL of the Symfony web server (used for loading images and assets)
fitsense.web.url=http://localhost:8000
# config.properties
jamendo.client.id=a9e7a0dc

# Database connection
db.url=jdbc:mysql://127.0.0.1:3306/fitsensee?serverTimezone=UTC&characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false
db.user=root
db.password=
