# FitSense Desktop Configuration
# URL of the Symfony web server (used for loading images and assets)
fitsense.web.url=http://localhost:8000
# config.properties
jamendo.client.id=a9e7a0dc

# Database connection
db.url=jdbc:mysql://127.0.0.1:3306/fitsense?serverTimezone=UTC&characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false
db.user=root
db.password=root

# API Keys (set these as environment variables or update here locally)
groq.api.key=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
sendgrid.api.key=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
